// <auto-generated />
using Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190929155618_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EAN");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhotoPath");

                    b.Property<float>("Qty");

                    b.Property<int>("Unit");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "g9IFYiz0iA",
                            EAN = "5902294001518",
                            Name = "Oranżada Fantazja Czerwona 330ml",
                            Qty = 1f,
                            Unit = 0
                        },
                        new
                        {
                            Id = "r1PskoTkWF",
                            EAN = "5902294004960",
                            Name = "Oranżada Fantazja Orange 330ml",
                            Qty = 1f,
                            Unit = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
